import type { Board } from './types';

export const DEFAULT_BOARD: Board = {
  id: 'board-001',
  title: 'Product Roadmap Q2 2026',
  columns: [
    { id: 'col-todo', title: 'To Do', order: 0, color: '#6366f1' },
    { id: 'col-inprogress', title: 'In Progress', order: 1, color: '#f59e0b' },
    { id: 'col-review', title: 'In Review', order: 2, color: '#8b5cf6' },
    { id: 'col-done', title: 'Done', order: 3, color: '#10b981' },
  ],
  cards: [
    {
      id: 'card-001',
      columnId: 'col-todo',
      title: 'Set up CI/CD pipeline for staging environment',
      description: 'Configure GitHub Actions to auto-deploy to staging on every push to the main branch. Include linting and test steps before deploy.',
      order: 0,
      label: 'chore',
      dueDate: '2026-05-02',
    },
    {
      id: 'card-002',
      columnId: 'col-todo',
      title: 'Design onboarding flow wireframes',
      description: 'Create low-fidelity wireframes for the 5-step user onboarding sequence. Share with team for async review.',
      order: 1,
      label: 'feature',
      dueDate: '2026-04-30',
    },
    {
      id: 'card-003',
      columnId: 'col-todo',
      title: 'Audit third-party dependencies for security vulnerabilities',
      description: '',
      order: 2,
      label: 'bug',
      dueDate: null,
    },
    {
      id: 'card-004',
      columnId: 'col-todo',
      title: 'Write unit tests for payment module',
      description: 'Cover all edge cases in the Stripe webhook handler and refund logic. Aim for 90%+ coverage.',
      order: 3,
      label: 'chore',
      dueDate: '2026-05-07',
    },
    {
      id: 'card-005',
      columnId: 'col-inprogress',
      title: 'Implement real-time notification system',
      description: 'Use WebSockets to push card move and comment notifications to all active board members. Fallback to polling for unsupported browsers.',
      order: 0,
      label: 'feature',
      dueDate: '2026-04-26',
    },
    {
      id: 'card-006',
      columnId: 'col-inprogress',
      title: 'Refactor authentication middleware',
      description: 'Extract JWT validation into a shared middleware. Remove duplicated auth logic across 12 route handlers.',
      order: 1,
      label: 'improvement',
      dueDate: '2026-04-25',
    },
    {
      id: 'card-007',
      columnId: 'col-inprogress',
      title: 'Build CSV export for analytics dashboard',
      description: 'Allow users to export filtered table data as CSV. Include all visible columns in the export.',
      order: 2,
      label: 'feature',
      dueDate: null,
    },
    {
      id: 'card-008',
      columnId: 'col-review',
      title: 'Mobile responsive layout for settings page',
      description: 'The settings page breaks on viewports below 768px. Fix layout stacking and input sizing.',
      order: 0,
      label: 'bug',
      dueDate: '2026-04-24',
    },
    {
      id: 'card-009',
      columnId: 'col-review',
      title: 'API rate limiting implementation',
      description: 'Add per-user rate limiting to all public API endpoints using Redis. Limit to 100 req/min per token.',
      order: 1,
      label: 'improvement',
      dueDate: '2026-04-28',
    },
    {
      id: 'card-010',
      columnId: 'col-done',
      title: 'Migrate database to PostgreSQL 16',
      description: 'Successfully migrated all production data from PostgreSQL 14 to 16. Zero downtime via logical replication.',
      order: 0,
      label: 'chore',
      dueDate: null,
    },
    {
      id: 'card-011',
      columnId: 'col-done',
      title: 'Redesign pricing page',
      description: 'Launched new 3-tier pricing layout with comparison table. A/B test running — control vs new.',
      order: 1,
      label: 'improvement',
      dueDate: null,
    },
    {
      id: 'card-012',
      columnId: 'col-done',
      title: 'Fix memory leak in background job processor',
      description: 'Identified and resolved unclosed DB connections in the nightly report job. Memory usage dropped 40%.',
      order: 2,
      label: 'bug',
      dueDate: null,
    },
  ],
};

export const LABEL_CONFIG: Record<string, { label: string; bg: string; text: string; dot: string }> = {
  bug: { label: 'Bug', bg: 'bg-red-50', text: 'text-red-600', dot: 'bg-red-500' },
  feature: { label: 'Feature', bg: 'bg-blue-50', text: 'text-blue-600', dot: 'bg-blue-500' },
  improvement: { label: 'Improvement', bg: 'bg-violet-50', text: 'text-violet-600', dot: 'bg-violet-500' },
  chore: { label: 'Chore', bg: 'bg-slate-100', text: 'text-slate-500', dot: 'bg-slate-400' },
};
